# Generated by Django 6.0.1 on 2026-01-15 12:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the food item', max_length=200)),
                ('calories', models.PositiveIntegerField(help_text='Number of calories in this item')),
                ('date_added', models.DateField(default=datetime.date.today, help_text='Date when the item was added')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp of creation')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp of last update')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag')),
            ],
            options={
                'verbose_name': 'Food Item',
                'verbose_name_plural': 'Food Items',
                'ordering': ['-date_added', '-created_at'],
                'indexes': [models.Index(fields=['date_added'], name='calorietrac_date_ad_16b5d0_idx')],
            },
        ),
    ]
